model:
  params:
    embed_dim: 4  # Latent Channel (C=4)
    
    lossconfig:
      target: ldm.modules.losses.contperceptual.LPIPSWithDiscriminator
      params:
        disc_start: 10000
        kl_weight: 0.000001
        disc_weight: 0.5
        disc_in_channels: 1
        
    ddconfig:
      ch: 64
      ch_mult: [1, 2, 4, 4]  # 4 levels. Downsampling happens at level 0->1, 1->2, 2->3. Total 2^3 = 8x.
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
      in_channels: 1
      out_ch: 1
      resolution: 96
      z_channels: 4          # Internal Latent Channel
      temp_res: 50           # Input frames
      f_t: 0                 # 0 means NO temporal downsampling. Output T=50.
      use_3d_conv: True