model:
  # base_learning_rate: 2e-5
  # target: models.vae3d.ReducioVAE
  params:
    embed_dim: 16

    lossconfig:
      target: ldm.modules.losses.contperceptual.LPIPSWithDiscriminator
      params:
        disc_start: 10001
        kl_weight: 1e-6
        disc_weight: 0.05
        use_adaptive_gan: True
        rec_weight: 1.0 
        loss_norm: 'l1'
        perceptual_weight: 0.1
        disc_loss_scale: 0.1
        use_groupnorm: False
        act_tanh: False

    ddconfig:
      ch: 128
      ch_in: 128
      f_t: 1 # 这个是下采样的次数 不是倍数
      out_ch: 1
      z_channels: 16
      resolution: 96
      in_channels: 1
      temp_res: 50
      ch_mult: [ 1,2,4,4]
      num_res_blocks: 2
      attn_resolutions: []
      use_3d_conv: True
      upsample_first: True
      use_checkpoint: True
      fp32_attention: True
      window_size: 128
